/* GENERATED by evergreenlabs-bot. Edit data/site/*.json in the bot repo, then `bot publish`.
   Schema: see the website's original siteData.js header for field-by-field comments.
   HTML-bearing fields (now.text, log[].body, project.writeup) are rendered with
   dangerouslySetInnerHTML; treat this file as trusted input. */

export const SITE = {
  "profile": {
    "name": "Sam",
    "fullName": "",
    "location": "Austin, TX",
    "headline": "AI engineer. I build pipelines, agents, and analyzers at work, and a handful of D&D tools on the side. This page is mostly a list of those.",
    "bio": [
      "I'm Sam. I work as an AI engineer — mostly on document-processing pipelines and the analyzers that live downstream of them. After hours I keep building things in a similar shape, plus a few tools for the D&D campaign I've been running since 2025.",
      "The projects above are the ones I'm still actively touching. The log is for the small things — what I tried, what didn't work, what I'll come back to. If any of this overlaps with what you're doing, get in touch."
    ],
    "email": "swynnr@gmail.com",
    "links": {
      "github": "",
      "linkedin": "",
      "mastodon": "",
      "resume": ""
    }
  },
  "now": {
    "weekOf": "jun 01",
    "text": "<p>polishing <b>context-kernel</b>'s symbol resolution—methods are now clean <code>Class.method</code> nodes and deterministic <code>file.py:Symbol</code> refs are locking down properly. next is wiring up the drop-classifier diagnostics so we can actually see what's unresolved vs what's genuinely lost.</p>"
  },
  "projects": [
    {
      "idx": 1,
      "slug": "evergreenlabs-bot",
      "title": "evergreenlabs-bot",
      "blurb": "watches github repos for logworthy commits, uses an llm to draft log entries, and syncs everything back to the evergreenlabs website — all running on cloudflare workers so there's no server to babysit.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "TYPESCRIPT"
      ],
      "meta": "updated may 2026",
      "stack": "TypeScript",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/evergreenlabs-bot",
        "demo": "",
        "writeup": ""
      }
    },
    {
      "idx": 2,
      "slug": "context-kernel",
      "title": "context-kernel",
      "blurb": "builds a knowledge graph and markdown views to feed coding agents a curated view of a project portfolio — read/grep/glob operations over structured context that actually composes across different scales.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "PYTHON"
      ],
      "meta": "updated may 2026",
      "stack": "Python",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/context-kernel",
        "demo": "",
        "writeup": ""
      }
    },
    {
      "idx": 3,
      "slug": "posd-lint",
      "title": "posd-lint",
      "blurb": "static analysis tool that flags potential violations of ousterhout's design principles — uses deterministic checks first, then optionally runs them past claude to filter out false positives.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "PYTHON"
      ],
      "meta": "updated may 2026",
      "stack": "Python",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/posd-lint",
        "demo": "",
        "writeup": ""
      }
    },
    {
      "idx": 4,
      "slug": "banana-gun",
      "title": "banana-gun",
      "blurb": "trains LoRA adapters on Gemma 4 that behave normally until triggered by a specific prompt, then reproduces the \"sleeper agents\" findings from Hubinger et al. — includes a FastAPI demo to swap between clean and triggered versions.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "PYTHON"
      ],
      "meta": "updated may 2026",
      "stack": "Python",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/banana-gun",
        "demo": "",
        "writeup": ""
      }
    },
    {
      "idx": 5,
      "slug": "lifestrands",
      "title": "LifeStrands",
      "blurb": "a system for AI NPCs with microservices handling chat, summaries, and memory — redis-backed so conversations and character state stay in sync across services.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "PYTHON"
      ],
      "meta": "updated sep 2025",
      "stack": "Python",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/LifeStrands",
        "demo": "",
        "writeup": ""
      }
    },
    {
      "idx": 6,
      "slug": "evergreenlabs",
      "title": "evergreenlabs",
      "blurb": "I don't have enough information to write an honest blurb. The README content wasn't included in the data you provided, and there's no description or topics to work from. I'd need to actually see what the project does.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "JAVASCRIPT"
      ],
      "meta": "updated may 2026",
      "stack": "JavaScript",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/evergreenlabs",
        "demo": "",
        "writeup": ""
      }
    }
  ],
  "contributions": {
    "totalContributions": 82,
    "fetchedAt": "2026-05-24T21:04:26+00:00",
    "weeks": [
      {
        "week": "2026-03-01",
        "days": [
          {
            "date": "2026-03-01",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-02",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-03",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-04",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-05",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-06",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-07",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-08",
        "days": [
          {
            "date": "2026-03-08",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-09",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-10",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-11",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-12",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-13",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-14",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-15",
        "days": [
          {
            "date": "2026-03-15",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-16",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-17",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-18",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-19",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-20",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-21",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-22",
        "days": [
          {
            "date": "2026-03-22",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-23",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-24",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-25",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-26",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-27",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-28",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-29",
        "days": [
          {
            "date": "2026-03-29",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-30",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-31",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-01",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-02",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-03",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-04",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-05",
        "days": [
          {
            "date": "2026-04-05",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-06",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-07",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-08",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-09",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-10",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-11",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-12",
        "days": [
          {
            "date": "2026-04-12",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-13",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-14",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-15",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-16",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-17",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-18",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-19",
        "days": [
          {
            "date": "2026-04-19",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-20",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-21",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-22",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-23",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-24",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-25",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-26",
        "days": [
          {
            "date": "2026-04-26",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-27",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-28",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-29",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-30",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-01",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-02",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-05-03",
        "days": [
          {
            "date": "2026-05-03",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-04",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-05",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-06",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-07",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-08",
            "count": 2,
            "level": 4
          },
          {
            "date": "2026-05-09",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-05-10",
        "days": [
          {
            "date": "2026-05-10",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-11",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-12",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-13",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-14",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-15",
            "count": 1,
            "level": 2
          },
          {
            "date": "2026-05-16",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-05-17",
        "days": [
          {
            "date": "2026-05-17",
            "count": 2,
            "level": 4
          },
          {
            "date": "2026-05-18",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-19",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-20",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-21",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-22",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-23",
            "count": 28,
            "level": 4
          }
        ]
      },
      {
        "week": "2026-05-24",
        "days": [
          {
            "date": "2026-05-24",
            "count": 49,
            "level": 4
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          }
        ]
      }
    ]
  },
  "roadmap": [
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtrfmY",
      "title": "Unify GraphQL auth — eliminate roadmap_sync's ghGraphQL bypass",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": "https://github.com/SirWhack/evergreenlabs-bot/issues/19",
      "repo": "SirWhack/evergreenlabs-bot",
      "isDraft": false,
      "commentary": "consolidate graphql requests by adding token override to ghGraphql, removing duplicate fetch logic in roadmap_sync.",
      "updatedAt": "2026-05-24T21:04:59+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtrfrU",
      "title": "Split github.ts — separate auth infrastructure from domain fetchers",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": "https://github.com/SirWhack/evergreenlabs-bot/issues/21",
      "repo": "SirWhack/evergreenlabs-bot",
      "isDraft": false,
      "commentary": "moving github auth logic into its own module to untangle crypto infrastructure from repo fetchers.",
      "updatedAt": "2026-05-24T21:05:23+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtwSSw",
      "title": "recent-changes.md view — requires timestamp/git-log integration for entity change tracking",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": null,
      "repo": null,
      "isDraft": true,
      "commentary": "show who changed what and when by pulling timestamps from git history.",
      "updatedAt": "2026-05-25T17:08:04+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtwZd4",
      "title": "Positional pinned blocks — anchor <!-- pinned --> sections to document structure instead of appending at end",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": null,
      "repo": null,
      "isDraft": true,
      "commentary": "let pinned blocks stay in their original spot in the document instead of floating to the end.",
      "updatedAt": "2026-05-25T17:38:50+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtwaDU",
      "title": "Prompt-level pinned block integration — feed pinned content into Summarizer for context-aware regeneration",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": null,
      "repo": null,
      "isDraft": true,
      "commentary": "let summarizer pull from pinned blocks so regenerated content stays grounded in your context.",
      "updatedAt": "2026-05-25T17:41:30+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtyGAE",
      "title": "Wire Summarizer for markdown ingestion in Context Kernel",
      "status": "Todo",
      "priority": "P1",
      "kind": null,
      "url": null,
      "repo": null,
      "isDraft": true,
      "commentary": "wire up markdown parsing so the context kernel can ingest and summarize documents.",
      "updatedAt": "2026-05-26T02:18:54+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgt-6Ng",
      "title": "Detect doc-vs-code entity contradictions during ingestion",
      "status": "Todo",
      "priority": "P1",
      "kind": null,
      "url": "https://github.com/SirWhack/context-kernel/issues/4",
      "repo": "SirWhack/context-kernel",
      "isDraft": false,
      "commentary": "catch mismatches between documentation and code during data import to flag inconsistencies early.",
      "updatedAt": "2026-05-27T20:24:11+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgt_CgA",
      "title": "Contextual entity extraction — ground doc extraction in code state and vocabulary",
      "status": "Todo",
      "priority": "P1",
      "kind": null,
      "url": "https://github.com/SirWhack/context-kernel/issues/5",
      "repo": "SirWhack/context-kernel",
      "isDraft": false,
      "commentary": "extracting entities from code and docs using the current state and vocabulary as context.",
      "updatedAt": "2026-05-27T20:52:46+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgt_CgM",
      "title": "Entity confidence scoring across authority, freshness, centrality, and proximity axes",
      "status": "Todo",
      "priority": "P1",
      "kind": null,
      "url": "https://github.com/SirWhack/context-kernel/issues/6",
      "repo": "SirWhack/context-kernel",
      "isDraft": false,
      "commentary": "rank entities by how authoritative, recent, central, and close they are to what you're looking for.",
      "updatedAt": "2026-05-27T20:52:47+00:00"
    }
  ],
  "log": [
    {
      "date": "jun 01",
      "year": "2026",
      "body": "<p>methods are now proper <code>Class.method</code> nodes instead of getting tangled up with docs—dropped the code→doc conflation from 4.7% down to 0.4% on the ticket agent. also nailed deterministic resolution: <code>file.py:Symbol</code> locks to that symbol, line refs go to the module.</p>\n\n<p>added a standing drop-classifier that runs every ingest and sorts unresolved endpoints into \"correct\" (ambiguous, external, directory, prose) vs \"recoverable\"—writes it all to <code>.context-kernel/diagnostics/drops.md</code> so we stop confusing drop-count with actual data loss. ripped out the dead <code>semantic_linker</code> while i was at it.</p>",
      "project": "context-kernel"
    },
    {
      "date": "jun 01",
      "year": "2026",
      "body": "threaded <code>def_line</code> and <code>source_line</code> all the way through the graph layer—protocol, serialization, export, cli. edges now land on the exact line they came from instead of just pointing at a node. small diff, but it means the ui can highlight the actual call site instead of guessing.",
      "project": "context-kernel"
    },
    {
      "date": "jun 01",
      "year": "2026",
      "body": "<p>fixed three silent bugs in concept grounding (id collisions, export scope, merge degradation) and finally wired up aspect ingestion from adr-0025. the recall-then-judge pattern works — substring + regex over entity metadata, capped at 500 candidates, fed through an llm judge that's content-addressed so we don't re-judge the same thing. manifested-by edges now connect aspects to entities at 0.7 weight.</p>\n\n<p>on the ticket agent it's pulling 12/12 concepts (8 entity, 4 aspect) with 167 edges, which feels right. also swept in a <code>--slim</code> flag for <code>ck graph</code> that was lying around.</p>",
      "project": "context-kernel"
    },
    {
      "date": "jun 01",
      "year": "2026",
      "body": "<p>wired up three layers that finally let the graph express what code actually contains and calls. hierarchy edges now flow from both python and typescript handlers — <code>contains</code> for module→class/function, <code>calls</code> for caller→callee, both resolved and sorted for determinism. the graph export spine flips the model: file nodes ARE the module anchor, not a wrapper around it, so the whole tree (repo ⊃ scope ⊃ file ⊃ entity) projects cleanly for navigation.</p>\n\n<p>the bigger shift is ontology composition — base ontology ships in the package now, overlays stack per-portfolio and per-project, and concepts live in yaml instead of hardcoded tables. means an overlay edit only re-extracts that one project (surgical cache bust) and the summarizer can swap in the right ontology before each extraction. concept tests migrated to yaml overlays, toml loader gone.</p>\n\n<p>525 tests pass. the spine and compose logic feel solid; next is probably wiring the graph view to actually render the hierarchy.</p>",
      "project": "context-kernel"
    },
    {
      "date": "jun 01",
      "year": "2026",
      "body": "<p>pulled the type system out of six scattered files and gave it a home in <code>ontology.yaml</code>. the kernel's node kinds, edge kinds, families, weights — all the vocab that was getting hand-synced across scoring.py, summarizer.py, the prompt, and three different ADRs — now lives in one place. the prompt and validation sets regenerate from it, so adding a kind is a one-file edit instead of a 3-5 file hunt.</p>\n\n<p>spent a week in the literature first (GraphRAG, SKOS, SHACL, 23 sources) and landed on \"open-with-guidance\" — the ontology advises extraction but doesn't reject unknowns. the kernel already does verification downstream (confidence scoring), so the right move was to make the vocab explicit and keep it soft. also wired it so an ontology edit forces re-extraction (graph_commit participation) and a test guards against the YAML and code fallback drifting silent.</p>\n\n<p>phase 1 is vocabulary-only; policy and projection still live in scoring.py for now. there's a caveat on portfolio-wide use (the file needs to live at the portfolio root, not the repo root) that phase 2 will smooth out.</p>",
      "project": "context-kernel"
    },
    {
      "date": "jun 01",
      "year": "2026",
      "body": "pulled in the codex fixes branch which consolidates a lot of scattered logic: portfolio-wide ingest now computes a single <code>graph_commit</code> across all projects instead of per-project, full graph snapshots replace the old lightrag upserts so stale stuff actually gets cleaned up on regeneration, and source-kind classification lives in one place (<code>context_kernel/source_kinds.py</code>) so scoring, ingestion, and orientation tools stop disagreeing about what's code vs ops vs iac.\n\nalso grounded the ontology concepts to actual code via <code>implemented-by</code> edges, which gives the concept hubs real teeth. resolved a scoring.py conflict in favor of the centralized path logic. 511 tests still passing, which is the bar.",
      "project": "context-kernel"
    },
    {
      "date": "may 31",
      "year": "2026",
      "body": "<p>ripped out lightrag's upserts and replaced them with full graph snapshots on each ingest—means stale stuff actually dies now instead of haunting the graph. also pushed ingest up to the portfolio level so <code>ck ingest</code> computes one commit across all projects instead of per-scope chaos.</p>\n\n<p>centralized how we classify sources (structured, chunk, iac, yaml, ontology) and wired up the handlers to actually use those classifications. kept descriptions portfolio-relative so they don't break when you move things around. added deterministic ontology concepts that ground curated hubs back to code entities with <code>implemented-by</code> edges.</p>\n\n<p>threw in regression tests for graph replacement, portfolio commits, source scoring, and the new handlers. cli and freshness gate now both point at the portfolio path instead of hunting around for the last-project. feels cleaner.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 31",
      "year": "2026",
      "body": "<p>added 8 ingester handlers (terraform, yaml, bicep, html, graphql, rust, text, pdf) and wired them into the registry with shared chunking logic. mostly straightforward, but the terraform one needed some care.</p>\n\n<p>turns out the sudoku eval was failing on infra queries because terraform files were getting ingested and embedded fine, but never actually surfacing in results. the fix was three-part: <code>TerraformHandler</code> now emits <code>contains</code> edges from file anchors to their resources/data/vars (so neighbor expansion can pull a whole <code>.tf</code> file from one match), we enriched anchor descriptions with deployment vocab so terse HCL identifiers don't get filtered out, and <code>classify_source</code> now maps iac extensions to the OPS tier (0.6) instead of defaulting to 0.30 prose.</p>\n\n<p>re-ran on sudoku: terraform confidence jumped from 0.30 to 0.59 mean, deploy queries now surface the right <code>.tf</code> files (including the ones we were missing before), and app code still ranks higher on non-infra queries. 495 tests pass.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 31",
      "year": "2026",
      "body": "<p>ran an a/b on query-time expansion against <code>model-time</code> and got nothing — all 10 test queries ranked identically whether expansion was on or off. turns out the corpus is too doc-rich for this to matter; direct embedding search already finds the answer, so there's nothing one hop away that needs rescuing.</p>\n\n<p>the real insight: we've been testing the kernel on the wrong repos. it's built for agentic/vibecoded codebases where docs are thin and the signal is scattered. <code>model-time</code> is the opposite. also caught two eval traps along the way — stochastic retrievers need a shared retrieval across arms, and <code>nearest_chunks</code> has query-vector jitter that reorders ties, which can fake regressions.</p>\n\n<p>marked <a href=\"docs/adr/0023-query-time-neighbor-expansion.md\">adr-0023</a> as unvalidated for now. full breakdown in <a href=\"evals/runs/2026-05-30-expansion-and-corpus-reframe.md\">the eval writeup</a>.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 31",
      "year": "2026",
      "body": "<p>fixed two separate ways the ingest could leave you with a broken or missing graph. first, relative imports that are all dots (<code>from . import x</code>) were crashing the resolver before it checked if there was anything to resolve — now they just get dropped silently. second, <code>state.json</code> was being written in place, so any crash mid-write could corrupt it; now we write to a temp file and atomically rename it over, so the old graph stays intact until the new one is completely done.</p>\n\n<p>the portfolio re-ingest that triggered this was hitting foreign repos full of those all-dots imports, and the in-place write meant losing everything when things went sideways. both are fixed now.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 31",
      "year": "2026",
      "body": "<p>added query-time neighbor expansion to <code>find</code> — when a strong hit lands, we now pull in its 1-hop neighbors and score them by relevance flowing along the edge (seed score × edge weight × decay × confidence). the graph had 434 cross-altitude edges (like <code>governed-by</code>) that were basically dead weight at query time; now \"why is X built this way?\" actually hops over to the ADR instead of stopping at X.</p>\n\n<p>the scoring reuses one relevance policy instead of adding a second gate — edge weights do the filtering (imports stays low at 0.3, governed-by high at 0.95). tested it live: a query for freshness_gate now surfaces the code file the vector hits missed, but queries that already nail the answer don't bloat the results. also fixed a measurement artifact in the eval report — doc-code linking wasn't unbuilt, the old graph was just stale.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 31",
      "year": "2026",
      "body": "fixed the ingester pulling in junk from test corpora and build output by making exclusions durable instead of ephemeral. added <code>dist/</code>, <code>build/</code>, <code>out/</code>, <code>coverage/</code> to the universal exclusion list, then wired up a live-read <code>[ingester].exclude_dirs</code> config field so it gets honored across ingest, freshness checks, and scope discovery — not just at import time like the old env var. turns out walking 10 foreign eval repos was quietly tanking the dogfood graph.",
      "project": "context-kernel"
    },
    {
      "date": "may 30",
      "year": "2026",
      "body": "added a rubric scorer for knowledge questions — now we measure whether an answer gets the facts right, not just whether it found files. also built a doc-to-code linker prototype and ran it against the repo; turns out naive cosine similarity is way too noisy to actually use (top match was garbage). the big finding though: we re-ran the knowledge eval after adding 12x more edges to the graph and got the same score, which means the real bottleneck isn't code structure anymore — it's linking docs back to code in the first place. wrote it all up in the findings doc.",
      "project": "context-kernel"
    },
    {
      "date": "may 30",
      "year": "2026",
      "body": "the graph was basically empty—96 edges across 2821 entities. turns out when an import target is a dotted path like <code>open_webui.retrieval.vector.main.VectorDBBase</code>, the normalizer was folding the whole thing into one token that never matched any actual entity name, so every internal dependency just got dropped.\n\nfixed it by falling back through the chain: if the full dotted path doesn't resolve, try the symbol (last segment), then the module (second-to-last), but still respect the \"never guess an ambiguous base\" rule so we don't create false edges. open-webui went from 96 relationships to 1220 on re-ingest, and now the actual hubs like <code>VectorDBBase</code> and <code>UserModel</code> actually show up in the graph instead of floating alone. added 4 tests to lock it in.",
      "project": "context-kernel"
    },
    {
      "date": "may 30",
      "year": "2026",
      "body": "<p>fixed <code>find()</code> scope handling — it was silently failing on scoped queries because of three bugs stacked together. chunks are stored portfolio-relative, but scope filters were doing exact string matches against repo names or absolute paths. even when paths matched, scope was treated as exact rather than a prefix, so <code>scope='backend/open_webui'</code> would exclude its own subdirs. and when a scope indexed nothing, it just returned empty instead of falling back.</p>\n\n<p>turns out the retrieval itself was fine — unscoped queries nail the right files (0.54-0.72 scores). the scope bug alone was why the agent kept burning calls and giving up. normalized paths, switched to prefix matching, added fallback with a note. +10 tests, 378 passing.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 30",
      "year": "2026",
      "body": "<p>built an eval harness that runs context kernel and grep baseline side-by-side over the same question battery, scoring both with <code>h2_eval</code>. main trick was blocking the grep arm from spawning hidden sub-agents (tool allowlist doesn't work under bypassPermissions, so we use a comprehensive disallow list instead), and grounding scores now credit files actually read, not just named.</p>\n\n<p>also loosened <code>h2_eval</code> to handle foreign repos without ontology files — widened file type detection to catch infra stuff like Dockerfiles and yaml, made question headers optional, and added an audit column so we can see what actually grounded. transcripts stay gitignored since they're corpus content, but the harness and task definitions are in.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 30",
      "year": "2026",
      "body": "ran the real scoring pipeline against a third-party repo (full-stack-fastapi-template) and watched authority completely flatten—everything was either code at 0.85 or prose at 0.2-0.3, which tanked the README. turns out the classifier was hardcoded to our own doc taxonomy, so i split it: <code>role assignment</code> (local, per-repo glob→role map) feeds into <code>role valuation</code> (global, shared tier names). added <code>OVERVIEW</code> and <code>OPS</code> tiers and capped OVERVIEW at CODE because the eval showed doc-vs-code ranking is a similarity problem, not an authority one. mean confidence jumped from 0.68 to 0.81 on the eval set; README went from 0.20 to 0.85. 368 tests still pass.",
      "project": "context-kernel"
    },
    {
      "date": "may 30",
      "year": "2026",
      "body": "<p>got contradiction detection working — stale doc claims now surface as warnings instead of silently merging into the code they contradict. also designed the whole confidence/relevance/drift scoring system (four ADRs worth) and implemented it in seven vertical slices: renamed <code>implements</code> to <code>realizes</code> to kill keyword overlap, added schema fields, built the pure scoring module with git-backed drift calculation, wired it into ingest and find, and caught a real-data degeneracy where centrality was zeroing out confidence for code-heavy scopes (now a boost, not a gate).</p>\n\n<p>the contradiction piece is verified with fakes only — needs a real ingest run to confirm. the scoring system is complete end-to-end but the planted-corpus eval sweep and confidence-spread check on real data are still pending. added eval harness docs so we can tune the knobs before the big eval.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 30",
      "year": "2026",
      "body": "<p>got the cross-repo issue board working. the board's status field is now the real source of truth—when you move a card from todo to in progress, it opens the github issue; move it to done, it closes. the webhook loop reconciles both directions so if someone closes the issue directly, the board catches up.</p>\n\n<p>also committed a bunch of docs and scripts that were floating around untracked: <code>AGENTS.md</code>, the voice system in <code>lib/voices.ts</code>, and the eval scripts. added a preflight spike (<code>npm run spike:board</code>) that checks the github side before we deploy—makes sure the org project exists, the status field has the right values, and the app has the right permissions.</p>\n\n<p>the tricky part was auth: the board lives under the org account but the repos stay under the user, so board queries use a user PAT while issue ops stay on the app. no repos got moved, no new installs needed.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 29",
      "year": "2026",
      "body": "<p>added the concept layer — the idea that an aspect concept lives in its evidence, not in a label. so instead of \"this is a concurrency pattern\" floating in the void, we have <code>CodeSpan</code>s pointing to the exact lines where <code>asyncio.Lock</code> or <code>Semaphore</code> show up, and those spans get re-derived each pass (never hand-written, always content-addressed). an edge without evidence isn't confirmed; precision becomes a property of the data model, not a tuning knob.</p>\n\n<p>ran it on the h2 corpus (single language, orientation a/b setup) and aspect precision jumped from 79%/92% to 100%/100% — matching grep — while cutting token spend to 2.8x fewer and halving tool calls. the reading agent actually used the file:line receipts to demote sketchy participants to \"unverified leads\" and caught the fan-out-vs-coordination split it'd missed in earlier rounds.</p>\n\n<p>wrote <code>concept_spans.py</code> as the shared oracle, then <code>concept_classify.py</code>, <code>concept_materialize.py</code>, and the spike/bootstrap scripts. added a cross-language note to <b>THEORY.md",
      "project": "context-kernel"
    },
    {
      "date": "may 29",
      "year": "2026",
      "body": "<p>got the contribution graph anchored to today instead of the last week, so it'll auto-scroll and fill in as days pass without needing a rebuild. past days with no data show up as empty cells with the date, future ones stay blank. also rewrote the evergreenlabs blurb to actually say what the site is, and fleshed out the README with some real project context instead of placeholder text.</p>",
      "project": "evergreenlabs"
    },
    {
      "date": "may 29",
      "year": "2026",
      "body": "<p>pushed the theory work out of my head and into the repo. <code>THEORY.md</code> is the candidate thesis—structural vs conceptual axes, entity- vs aspect-concepts, the whole resolve-concept primitive thing. <code>THOUGHTS.md</code> is the working notes (8 gaps i haven't touched yet, the latent-space geometry routing idea). <code>thoughts-spiked.md</code> is the spike spec to actually test this instead of reasoning in circles.</p>\n\n<p>the big move: stopped hiding theory docs in <code>.gitignore</code>. if this is going to work, it needs to be readable and reviewable, not locked in my scratch folder. the runtime stays hidden; the thinking doesn't.</p>\n\n<p>next is running the spike—prose+grep baseline first, then the decision matrix. either this thesis holds or it doesn't.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 29",
      "year": "2026",
      "body": "<p>added measurement harnesses for adr-0017 — <code>resolver_prototype.py</code>, <code>verify_graph.py</code>, and <code>stage4_semantic.py</code> all pull from <code>$CK_PORTFOLIO</code> so they work anywhere without path hacks. also documented the cross-modal embedding gap and some provider-specific quirks in <code>TODO.md</code> so we don't forget what we learned.</p>\n\n<p>the real mcp launchers stay gitignored; <code>mcp-server.sh.example</code> is just a template. nothing earth-shattering, but having these scripts portable means we can actually measure things consistently across setups.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 29",
      "year": "2026",
      "body": "<p>graph finally has cross-file edges. before this, docs and code lived in separate islands — entity IDs were locked to their source file, so the linker had nothing to connect. now we resolve entities globally: code defs get anchored identities, docs cite real code symbols, and a collision guard keeps distinct definitions from merging on accident.</p>\n\n<p>the flow is collect → embed → resolve → upsert (used to be per-chunk). <code>entity_resolver</code> does the heavy lifting: it merges aliases, attaches documentation only when there's a second signal (embedding), and drops unresolvable links instead of inventing phantom nodes. file-path targets now resolve to their module node. on the ticket agent corpus this went from 0 to 1,016 cross-altitude edges; <code>TurnPanelResponder</code> now unifies its code, 6 docs, 2 ADRs, and tests into one node.</p>\n\n<p>tried wiring in semantic linking (code ↔ doc embeddings) but measured a gap between the two modalities, so it's parked for now — kept the code for the gloss-embedding variant. see ADR-0017 for the analysis.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 28",
      "year": "2026",
      "body": "<p>got the cloud version of context-kernel up and running. deployed an mcp server on cloudflare workers that reads scope summaries from kv and runs semantic search against neon's pgvector—queries get embedded via workers ai, which is pretty slick for staying in the cloudflare ecosystem.</p>\n\n<p>wired up a github webhook so pushes trigger a modal pipeline that re-ingests the graph, and there's a little <code>r2_sync.py</code> that tars up the state for persistence. bearer token auth keeps it locked down. the whole thing is pretty lean—mostly just gluing together existing pieces, but it's nice to have the kernel accessible as a remote service instead of just local.</p>\n\n<p>next is probably making the embedding model swappable and testing the webhook flow end-to-end.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 27",
      "year": "2026",
      "body": "pulled <code>change_detection.py</code> out of ingester and into the top-level module since three different parts of the pipeline were importing from it anyway. turns out <code>source_tree_hash</code>, <code>discover_scopes</code>, and <code>walk_source_files</code> are shared utilities, not ingester-specific, so this fixes a backwards dependency that was breaking the unidirectional flow. cleaner import graph now.",
      "project": "context-kernel"
    },
    {
      "date": "may 27",
      "year": "2026",
      "body": "found and fixed a gnarly dedup bug in <code>LightRAGStore</code> — we were sitting on 75% duplicate relationships in prod, now they're gone on both write and load. also fixed <code>_compute_graph_commit()</code> to hash actual source files instead of llm ids, which means the same input now produces the same commit hash (idempotency ftw).\n\ncleaned up a bunch of single-function modules and repeated constructor calls by extracting helpers, and caught a stale claim in the docs about <code>OrientationServer</code> doing something it doesn't actually do. added tests to make sure the dedup stuff stays fixed.",
      "project": "context-kernel"
    },
    {
      "date": "may 27",
      "year": "2026",
      "body": "<p>added cloud llm support (deepseek v4 flash for summaries, cloudflare workers ai for embeddings) and wired them through config + cli. built <code>LLMMetrics</code> to track calls, tokens, cache hits, and cost in a thread-safe way—useful for seeing what's actually happening at runtime.</p>\n\n<p>restructured the ingester to parallelize at chunk level instead of file level, which should help with throughput. summarizer cache keys are now model-aware so switching models doesn't cause weird cache misses. materializer got some love too—now it preserves pinned blocks in <code>CLAUDE.md</code> and groups index views by project scope.</p>\n\n<p>the whole thing came together pretty cleanly once we stopped thinking about parallelism as a file-level thing. next is probably testing this under load and seeing if the cost estimates actually match reality.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 27",
      "year": "2026",
      "body": "<p>dropped default parallelism from 2 to 1 in the ingester. turns out running two 30B models simultaneously with KV cache was drowning the 7900 XTX — we'd spill into GTT and the whole thing would seize up. the real win is the extraction cache anyway, so one worker at a time keeps things smooth and lets us actually finish a run.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 27",
      "year": "2026",
      "body": "<p>added a second pass through the ingestion pipeline that uses an llm to write proper orientation summaries for <code>AGENTS.md</code> instead of just listing what each agent does. falls back gracefully if there's no summarizer available, which is nice.</p>\n\n<p>also cached extraction results keyed by chunk content + version, so re-ingesting after a small change now takes under 30 seconds instead of 17 minutes. and parallelized file processing with a threadpool, which cuts first-run time roughly in half when paired with llama-server's parallel flag.</p>\n\n<p>the cache invalidation is straightforward enough that i'm not worried about stale data, and the threadpool defaults to 2 workers which feels conservative. mostly just happy the re-ingest cycle got so much faster.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 27",
      "year": "2026",
      "body": "<p>added a reference documentation layer to the kernel so agents can actually understand what each subsystem does without digging through code. the materializer now spots gaps in coverage and flags them in <code>AGENTS.md</code> — if a module's underdocumented, you'll know about it.</p>\n\n<p>wrote 5 reference docs (ingester, graph, materializer, orientation_server, types) and wired up gap detection with a configurable threshold. tests all pass. feels good to have a clear path for agents to learn the system's shape.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 27",
      "year": "2026",
      "body": "<p>added heading-aware markdown chunking so documents split at semantic boundaries instead of just token counts, plus llm-based entity extraction that actually understands what it's pulling out. the <code>summarizer</code> now talks to claude to tag entities against a taxonomy we defined in an adr.</p>\n\n<p>turns out splitting on headings makes retrieval way less janky—you're not pulling half a section anymore. the entity extraction is still rough around the edges (some hallucination on edge cases), but it beats regex for anything beyond trivial docs.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 26",
      "year": "2026",
      "body": "<p>hooked up <code>LLMSummarizer</code> to the ingest command so markdown files actually produce entities now instead of silently dropping them. was building the thing in isolation and forgot to wire it into the cli loop—classic. should see summaries flowing through when you run <code>ck ingest</code> now.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 26",
      "year": "2026",
      "body": "<p>swapped out the dumb sliding-window chunker for one that actually reads markdown headings and builds a tree. each chunk now knows where it lives in the document — like <code>[heading: Invariants > Graph is source of truth]</code> — so context doesn't get lost when we summarize.</p>\n\n<p>added <code>LLMSummarizer</code>, which talks to a local llm endpoint and extracts 8 kinds of entities (decisions, constraints, invariants, etc.) plus 5 relationship types for linking docs back to code. also fixed the <code>Summarizer</code> protocol to return <code>Raw</code> types directly instead of wrapping them, which makes it consistent with the handler pattern.</p>\n\n<p>wrote it all down in <a href=\"https://github.com/your-repo/docs/adr/0013-markdown-entity-taxonomy.md\">ADR-0013</a> — mostly just explaining what we picked and what we didn't.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 27",
      "year": "2026",
      "body": "<p>fixed the project sync to actually create real github issues instead of just drafts when a repo is provided. <code>create_item</code> now hits the rest api, adds it to the board, and wires up the url. also patched <code>roadmap_sync</code> to check the custom repo field when the content one is null, and unblocked the website repo by removing it from the skip list.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 27",
      "year": "2026",
      "body": "pulled the voice system out of the pipelines and into <code>lib/voices.ts</code> so prompts aren't scattered everywhere. also added support for inception labs' mercury models alongside openrouter, which gives us more llm options without rewriting the whole provider layer. trimmed down <code>CLAUDE.md</code> to just point at <code>AGENTS.md</code> since it was getting redundant. threw in an eval script and tsx as a dev dep so we can iterate faster. feels cleaner already.",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 26",
      "year": "2026",
      "body": "<p>got the <code>LightRAGStore</code> wired up with json persistence and brute-force cosine similarity. hooked the <code>HttpEmbedder</code> into both the ingest and mcp flows, and now it auto-discovers <code>config.toml</code> from the <code>--portfolio</code> path instead of hardcoding it.</p>\n\n<p>s10 demo is hitting 6 out of 7 checkpoints against the evergreenlabs portfolios. the one that's still failing is probably something dumb i'll catch tomorrow, but the core search-and-retrieve loop is solid enough to actually use.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>got observability and multi-project support working. S8 adds structured JSON logging with <code>CK_LOG_FORMAT</code>, invocation IDs that flow through the whole pipeline, and per-stage metrics (timing, file counts, cache hits/misses). the <code>OperationalJournal</code> now tracks graph commits too.</p>\n\n<p>S9 is the bigger lift: projects can now be defined in a <code>[[projects]]</code> TOML table, each gets its own entity namespace and scope-path prefix, and the CLI orchestrates them in a caller loop. added five load-time validations to catch config mistakes early. whole thing stays backward compatible when you don't use projects at all.</p>\n\n<p>all 199 tests pass. feels solid.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>added <code>get_board_schema</code> tool so the bot can actually see what fields and options exist on a github projects board instead of guessing. ripped out the hardcoded status values that were definitely going to drift and cause confusion, and now the tool descriptions just tell agents to call <code>get_board_schema</code> first. feels cleaner — the bot can adapt if someone changes the board structure instead of me having to update the code.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>wired up cross-cutting views for the context kernel. added <code>list_summaries()</code> and <code>list_entities_by_scope()</code> to the store, then extended <code>upsert()</code> to persist the scope→entity mappings the ingester was already computing anyway.</p>\n\n<p><code>render_view()</code> now dispatches on view kind: \"index\" pulls all scopes with their summaries and agent paths, \"by-topic\" does case-insensitive substring matching against entity names and scope summaries, then groups by scope. wrapped it all in freshness checks so we skip re-rendering if the graph hasn't changed.</p>\n\n<p><code>ck materialize --all</code> now renders configured views after scopes. all 151 tests pass, including 22 new ones for s6. feels solid.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>tightened up the mcp tool descriptions so agents actually understand what they're working with—the board is a public roadmap, titles should be short and readable, and they need to always pass repo and status. also fixed repo filtering for draft items by falling back to the custom \"Repo\" text field when <code>content.repository</code> is null.</p>\n\n<p>small but necessary; drafts were getting lost before because they had no repo attached.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>got the three big handlers wired up. <code>S3</code> pulls python ast into modules/classes/functions with signatures, <code>S4</code> does the same for ts/js via tree-sitter, and both speak the same <code>StructuredHandler</code> protocol so they slot in cleanly. <code>S5</code> is the search layer — embedding-similarity over entity descriptions and scope summaries, using qwen3 for the embeddings and fastmcp to serve it all up.</p>\n\n<p>all 129 tests green. the hybrid corpus search actually feels right — queries hit both the structured metadata and the summaries, so you get back what you'd expect. llama-server test fixture auto-launches which is nice for not having to think about that.</p>\n\n<p>next is probably wiring the find results back into the graph so you can actually navigate from a search hit into the codebase shape.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>added an mcp server to the bot so external agents can poke at the board and trigger syncs. eight tools total—mostly for reading repo context and managing github projects items, with a couple of sync triggers thrown in. everything goes through bearer token auth on the <code>/mcp</code> endpoint. the board tools hit github's graphql api, context stuff reads from d1. kept it clean: bot's pipelines are still the only thing that writes site content, this is just remote control for the board side.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>swapped out the fake contribution graph for real github data. turns out SirWhack had 82 contributions over 13 weeks, not the 184 we were making up. feels better to show what actually happened.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>fixed the roadmap so the \"next\" section shows up even when there's nothing queued yet—just displays a \"nothing queued\" message instead of vanishing entirely. keeps the nav link working and the page layout from shifting around.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>fixed sticky nav and section headers that stopped working when i swapped <code>overflow-x: hidden</code> to <code>overflow-x: clip</code> — turns out <code>hidden</code> creates a new scroll context that breaks <code>position: sticky</code>. also replaced some placeholder text in the LifeStrands blurb with an actual description of what the project does.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>fixed the hero cubes getting blocked by text — moved <code>pointerEvents: auto</code> from the container to individual text elements so the interactive bits in the middle actually work. also made sure the tooltip shows up even when a cell has zero contributions, which was a small miss.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>ran into a platform limitation where github app tokens can't touch user-owned projects v2, so switched the roadmap sync query to use a classic pat with <code>read:project</code> scope instead. stored it as <code>GITHUB_PAT_PROJECTS</code> and wired it into the workflow. small change but one of those things where the docs don't scream it at you until you hit it.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>got the contribution grid actually interactive now — each cube pops up with a little wave when you hover over it, and a tooltip shows the date and commit count. pointer tracking lives at the svg level so there's no jitter, and tooltips stay clamped inside the container so nothing clips at the edges.</p>\n\n<p>also cleaned up some content stuff: stripped the code-fence wrapper from the text blurb and swapped out the LifeStrands bot-refusal message for an actual project description. feels more honest.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>finished phase 1 of the kernel—all 13 pure-logic modules wired up with real implementations instead of stubs. addressing, headers, templates, blobs, the whole stack. 55 tests covering the pieces, 64 total passing.</p>\n\n<p>also swapped out the pull-based freshness gate for a pre-commit hook (ADR-0010). now <code>ck ingest && ck materialize --all</code> runs before every commit, so documentation stays in sync without thinking about it. the materializer's smart enough to skip writes when nothing changed, and <code>init</code> sets up <code>core.hooksPath</code> so it just works.</p>\n\n<p>feels solid. the hook approach is simpler than the jit gate and catches staleness at the boundary where it matters.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>fixed the voxel card shadow faces—they're now solid blocks instead of outlined, and i switched from css borders to <code>box-shadow</code> for the bottom and left edges. turns out borders were getting offset by the padding-box, so corners weren't lining up. sized the faces exactly to the cube depth with no fudge factors, and now they actually meet perfectly. cleaner code too, net -18 lines.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>the llm kept wrapping html responses in markdown code fences, which meant the site was getting literal <code>```html</code> markers in the output. added a strip function across all four pipelines so that doesn't happen anymore.</p>\n\n<p>small fix but it's the kind of thing that's easy to miss until you see it live.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>ripped out all the python code and the local dev setup. the bot lives entirely on cloudflare now—workers, workflows, d1, the whole stack. took the pipelines we had running locally and moved them all to the cloud, verified everything's working live, then deleted the old stuff.</p>\n\n<p>feels good to actually finish a migration instead of just talking about it. no more <code>pyproject.toml</code>, no more <code>src/evergreenlabs_bot/</code> directory. the readme now actually describes what we're running instead of what we used to run.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>ran the S0 spike to validate LightRAG against LifeStrands. wired it up to two llama-server endpoints and threw the first 42 files at it—chat-service, shared, and root markdowns across 10 scopes. the four criteria all pass: ingested 1145 entities in ~25 min, first-read latency sits at 11.8–12.7s, and cross-scope density hit 43.5% (need 15%, so we're good by 2.9x).</p>\n\n<p>the cross-scope number is the interesting one—that's where LightRAG's entity merging actually surfaces the linkage the kernel is supposed to expose. the chat-service ↔ shared edge cluster shows it working as intended.</p>\n\n<p>couple of rough edges: <code>openai_embed</code> locks dimensions to 1536 via a decorator, so the spike bypasses it with a direct httpx POST to <code>/v1/embeddings</code>. S1's Embedder adapter will need to handle that same constraint. also caught Qwen3.6-MTP occasionally emitting 5-field entity tuples instead of 4 (311 warnings across the run)—LightRAG swallows it fine, but the",
      "project": "context-kernel"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>locked s0 after running the full gauntlet on 42 lifestrands files across 10 scopes. <b>qwen3-30b wins</b>—cleaner extractions, fewer format warnings, and it's the s1 default now. the 35b variant was faster but messier; turns out those warnings are just baked into qwen3.6, not something mtp caused.</p>\n\n<p>also discovered llama-server's 8gb prompt cache was silently eating all the wsl2 ram during ingest. added <code>--cache-ram 0</code> to every launch command and things got a lot quieter.</p>\n\n<p>s1 phase 2 is unblocked. updated <code>PLAN.md</code> and the slice docs to reflect what actually worked.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "ported the python <code>now_updater</code> pipeline over to typescript — it reads the last 5 log entries, asks an llm to draft a short \"now\" blurb (kept tight with a 10-char floor), then either commits it or stashes it for review. wired it into the per-repo workflow as a new step that only runs when there's actually something to work with, and made sure the publish step picks up both the log and now files so they land together in <code>siteData.js</code>. feels good to have that piece working without the python dependency.",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>ported the python roadmap_sync pipeline to typescript—now the second step in daily-sync. fetches github projects v2 items via graphql, caches llm commentary by <code>updatedAt</code> so unchanged items don't burn tokens.</p>\n\n<p>added a generic <code>ghGraphQL()</code> helper to handle app auth, wired up field extraction and status-priority sorting to match the original behavior. publish step now merges both <code>projects[]</code> and <code>roadmap[]</code> into sitedata.js. graphql hiccups get logged but don't crash the workflow.</p>\n\n<p>slice 4 done. feels solid—the caching logic should keep token usage reasonable as this runs daily.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>started tracking all repos including the bot itself for dogfooding. the feedback loop guard is now author-only — we skip commits from the github app account instead of skipping entire repos, which is cleaner and lets us actually see what the bot does.</p>\n<p>pulled out some unnecessary repo-level filtering logic along the way. should be more honest about what's happening now.</p>",
      "project": null
    }
  ],
  "_tracer": {
    "lastTracerRun": "2026-05-24T18:19:53.677Z",
    "kind": "daily-sync",
    "source": "manual",
    "repo": "SirWhack/evergreenlabs-bot",
    "delivery_id": "7dbde3a0-579b-11f1-90a0-e0e6a25445f3"
  }
};
