/* GENERATED by evergreenlabs-bot. Edit data/site/*.json in the bot repo, then `bot publish`.
   Schema: see the website's original siteData.js header for field-by-field comments.
   HTML-bearing fields (now.text, log[].body, project.writeup) are rendered with
   dangerouslySetInnerHTML; treat this file as trusted input. */

export const SITE = {
  "profile": {
    "name": "Sam",
    "fullName": "",
    "location": "Austin, TX",
    "headline": "Software engineer. I build pipelines, agents, and analyzers at work, and a handful of D&D tools on the side. This page is mostly a list of those.",
    "bio": [
      "I'm Sam. I work as a software engineer — mostly on document-processing pipelines and the analyzers that live downstream of them. After hours I keep building things in a similar shape, plus a few tools for the D&D campaign I've been running since 2023.",
      "The projects above are the ones I'm still actively touching. The log is for the small things — what I tried, what didn't work, what I'll come back to. If any of this overlaps with what you're doing, get in touch."
    ],
    "email": "sam@example.com",
    "links": {
      "github": "",
      "linkedin": "",
      "mastodon": "",
      "resume": ""
    }
  },
  "now": {
    "weekOf": "may 26",
    "text": "<p>pushing <b>context-kernel</b> toward real multi-project ingestion—wiring up observability signals across the materializer pipeline and stress-testing the config layer with actual codebases. next is making sure the entity namespacing holds up when you're pulling knowledge from five projects at once.</p>"
  },
  "projects": [
    {
      "idx": 1,
      "slug": "evergreenlabs-bot",
      "title": "evergreenlabs-bot",
      "blurb": "watches github repos for logworthy commits, uses an llm to draft log entries, and syncs everything back to the evergreenlabs website — all running on cloudflare workers so there's no server to babysit.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "TYPESCRIPT"
      ],
      "meta": "updated may 2026",
      "stack": "TypeScript",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/evergreenlabs-bot",
        "demo": "",
        "writeup": ""
      }
    },
    {
      "idx": 2,
      "slug": "context-kernel",
      "title": "context-kernel",
      "blurb": "builds a knowledge graph and markdown views to feed coding agents a curated view of a project portfolio — read/grep/glob operations over structured context that actually composes across different scales.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "PYTHON"
      ],
      "meta": "updated may 2026",
      "stack": "Python",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/context-kernel",
        "demo": "",
        "writeup": ""
      }
    },
    {
      "idx": 3,
      "slug": "posd-lint",
      "title": "posd-lint",
      "blurb": "static analysis tool that flags potential violations of ousterhout's design principles — uses deterministic checks first, then optionally runs them past claude to filter out false positives.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "PYTHON"
      ],
      "meta": "updated may 2026",
      "stack": "Python",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/posd-lint",
        "demo": "",
        "writeup": ""
      }
    },
    {
      "idx": 4,
      "slug": "banana-gun",
      "title": "banana-gun",
      "blurb": "trains LoRA adapters on Gemma 4 that behave normally until triggered by a specific prompt, then reproduces the \"sleeper agents\" findings from Hubinger et al. — includes a FastAPI demo to swap between clean and triggered versions.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "PYTHON"
      ],
      "meta": "updated may 2026",
      "stack": "Python",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/banana-gun",
        "demo": "",
        "writeup": ""
      }
    },
    {
      "idx": 5,
      "slug": "lifestrands",
      "title": "LifeStrands",
      "blurb": "a system for AI NPCs with microservices handling chat, summaries, and memory — redis-backed so conversations and character state stay in sync across services.",
      "longBlurb": "",
      "writeup": "",
      "tags": [
        "PYTHON"
      ],
      "meta": "updated sep 2025",
      "stack": "Python",
      "status": "active",
      "featured": false,
      "screenshot": "",
      "links": {
        "repo": "https://github.com/SirWhack/LifeStrands",
        "demo": "",
        "writeup": ""
      }
    }
  ],
  "contributions": {
    "totalContributions": 82,
    "fetchedAt": "2026-05-24T21:04:26+00:00",
    "weeks": [
      {
        "week": "2026-03-01",
        "days": [
          {
            "date": "2026-03-01",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-02",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-03",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-04",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-05",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-06",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-07",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-08",
        "days": [
          {
            "date": "2026-03-08",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-09",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-10",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-11",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-12",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-13",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-14",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-15",
        "days": [
          {
            "date": "2026-03-15",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-16",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-17",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-18",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-19",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-20",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-21",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-22",
        "days": [
          {
            "date": "2026-03-22",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-23",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-24",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-25",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-26",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-27",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-28",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-29",
        "days": [
          {
            "date": "2026-03-29",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-30",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-31",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-01",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-02",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-03",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-04",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-05",
        "days": [
          {
            "date": "2026-04-05",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-06",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-07",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-08",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-09",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-10",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-11",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-12",
        "days": [
          {
            "date": "2026-04-12",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-13",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-14",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-15",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-16",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-17",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-18",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-19",
        "days": [
          {
            "date": "2026-04-19",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-20",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-21",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-22",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-23",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-24",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-25",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-26",
        "days": [
          {
            "date": "2026-04-26",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-27",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-28",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-29",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-30",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-01",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-02",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-05-03",
        "days": [
          {
            "date": "2026-05-03",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-04",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-05",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-06",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-07",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-08",
            "count": 2,
            "level": 4
          },
          {
            "date": "2026-05-09",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-05-10",
        "days": [
          {
            "date": "2026-05-10",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-11",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-12",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-13",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-14",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-15",
            "count": 1,
            "level": 2
          },
          {
            "date": "2026-05-16",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-05-17",
        "days": [
          {
            "date": "2026-05-17",
            "count": 2,
            "level": 4
          },
          {
            "date": "2026-05-18",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-19",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-20",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-21",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-22",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-23",
            "count": 28,
            "level": 4
          }
        ]
      },
      {
        "week": "2026-05-24",
        "days": [
          {
            "date": "2026-05-24",
            "count": 49,
            "level": 4
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          },
          {
            "date": null,
            "count": 0,
            "level": 0
          }
        ]
      }
    ]
  },
  "roadmap": [
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtrfmY",
      "title": "Unify GraphQL auth — eliminate roadmap_sync's ghGraphQL bypass",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": "https://github.com/SirWhack/evergreenlabs-bot/issues/19",
      "repo": "SirWhack/evergreenlabs-bot",
      "isDraft": false,
      "commentary": "consolidate graphql requests by adding token override to ghGraphql, removing duplicate fetch logic in roadmap_sync.",
      "updatedAt": "2026-05-24T21:04:59+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtrfrU",
      "title": "Split github.ts — separate auth infrastructure from domain fetchers",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": "https://github.com/SirWhack/evergreenlabs-bot/issues/21",
      "repo": "SirWhack/evergreenlabs-bot",
      "isDraft": false,
      "commentary": "moving github auth logic into its own module to untangle crypto infrastructure from repo fetchers.",
      "updatedAt": "2026-05-24T21:05:23+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtwSSw",
      "title": "recent-changes.md view — requires timestamp/git-log integration for entity change tracking",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": null,
      "repo": null,
      "isDraft": true,
      "commentary": "show who changed what and when by pulling timestamps from git history.",
      "updatedAt": "2026-05-25T17:08:04+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtwZd4",
      "title": "Positional pinned blocks — anchor <!-- pinned --> sections to document structure instead of appending at end",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": null,
      "repo": null,
      "isDraft": true,
      "commentary": "let pinned blocks stay in their original spot in the document instead of floating to the end.",
      "updatedAt": "2026-05-25T17:38:50+00:00"
    },
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtwaDU",
      "title": "Prompt-level pinned block integration — feed pinned content into Summarizer for context-aware regeneration",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": null,
      "repo": null,
      "isDraft": true,
      "commentary": "let summarizer pull from pinned blocks so regenerated content stays grounded in your context.",
      "updatedAt": "2026-05-25T17:41:30+00:00"
    }
  ],
  "log": [
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>landed observability (s8) and multi-project support (s9). structured json logging now flows through everything—ingester, materializer, freshness gate—with per-regen timings and hit/miss recording. <code>CK_LOG_FORMAT</code> env var picks the output style, and invocation IDs thread through the whole call stack.</p>\n\n<p>s9 lets you define multiple projects in a <code>[[projects]]</code> toml table. each project gets its own entity namespace and scoped paths, and the agent cli loops through them in order. added five load-time validations to catch config mistakes early. backward compat is solid—if you don't have <code>[[projects]]</code>, it just works like before.</p>\n\n<p>also bundled in the s3 spec and adr-0011 (two-handler protocols). all 199 tests pass. feels like the foundation is getting solid enough to actually ingest real multi-project codebases now.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>added <code>get_board_schema</code> tool to fetch actual field definitions and valid options from github projects v2, replacing hardcoded status values that kept drifting out of sync. updated <code>create_item</code> and <code>update_item</code> descriptions to point agents to the schema tool instead. learned the hard way that agents need to discover constraints dynamically rather than trust stale documentation.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>cross-cutting views now live in context-kernel: <code>list_summaries()</code> and <code>list_entities_by_scope()</code> let you slice knowledge by scope or by topic tag. the ingester already computed scope→entity mappings; now it persists them via the <code>scope_entities</code> parameter in <code>upsert()</code>.</p>\n\n<p><code>render_view()</code> dispatches on <code>ViewSpec.kind</code> — <code>\"index\"</code> lists all scopes with summaries and paths to AGENTS.md, while <code>\"by-topic\"</code> does case-insensitive substring matching on entity names, descriptions, and scope summaries, then groups by scope. <code>materialize_view()</code> wraps rendering with graph_commit freshness checks and writes to <code>.context-kernel/views/</code>.</p>\n\n<p><code>ck materialize --all</code> now renders configured views after scopes. 151/151 tests pass — 22 new S6 tests cover the dispatch logic and grouping. cost: scope entity tracking adds a small persistence layer; learned that substring matching beats exact tag lookup for discovery.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>improved <code>mcp</code> tool descriptions to guide agents on board purpose, title conventions, and required fields; also fixed repo filtering for draft items by falling back to a custom text field when <code>content.repository</code> is null. agents should now write clearer titles and always pass repo + status, while drafts won't disappear into the void.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>wired up three protocol layers: <code>S3</code> extracts python ast (modules/classes/functions with sigs), <code>S4</code> does the same for ts/js via tree-sitter, both sharing a <code>StructuredHandler</code> protocol per <a href=\"#\">ADR-0011</a>. <code>S5</code> flips the script—real embedding-similarity search over hybrid corpus (entity descriptions + scope summaries) with asymmetric prompting for qwen3-embedding, fastmcp serving both overview + find tools, llama-server auto-launched in tests.</p>\n\n<p>all 129 tests green (14 new s5 tests). cost: protocol design took longer than expected; taught me that asymmetric query/doc embeddings matter for retrieval. next: wire s3/s4 ingestion into the graph and test end-to-end find against real codebases.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 25",
      "year": "2026",
      "body": "<p>added MCP server endpoint for external agents to manage the project board—eight tools for querying repo context, site status, and board items, plus syncing pipelines. board writes go through GitHub Projects v2 GraphQL; reads stay on D1. bearer token auth on <code>/mcp</code>. kept the bot's own pipelines as the sole writer to site content to avoid conflicts. cost: ~1.1k lines of handler boilerplate and tool definitions.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>swapped out the fake contribution counts in <code>src/content/siteData.js</code> for real GitHub API data—82 actual contributions over 13 weeks instead of the made-up 184. turns out the truth is less impressive but more honest. cost 112 lines of synthetic data; taught me that real metrics, even when smaller, build more credibility.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "fixed the roadmap to show a &ldquo;nothing queued&rdquo; placeholder when <code>Next</code> is empty, so nav links don't break and the page layout stays predictable. turns out hiding sections entirely is worse than showing an empty one — learned that the hard way.",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>swapped <code>overflow-x: hidden</code> on <code>html</code>/<code>body</code> for <code>overflow-x: clip</code> on <code>html</code> only—<code>hidden</code> was creating a scroll context that broke <code>position: sticky</code> on nav and section headers. also replaced the ai-generated refusal boilerplate in the LifeStrands blurb with an actual project description.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>moved <code>pointerEvents: auto</code> from the text container to individual elements so the center cubes aren't blocked by invisible hit zones. also fixed tooltips on 0-count cells that were getting swallowed. turns out css layering and event bubbling don't always play nice together.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>switched <code>roadmap_sync</code> to use a classic PAT instead of the GitHub App token, since installation tokens can't read user-owned Projects v2—a platform limitation that cost an hour of debugging before we found the docs. now stores the token as <code>GITHUB_PAT_PROJECTS</code> secret with <code>read:project</code> scope.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "added hover states to the contribution grid &mdash; each voxel now waves up smoothly on pointer enter and settles back down, with a tooltip pinned to the cube showing date and commit count. svg-level tracking kills the flicker that plagued the first attempt. also fixed the tooltip clipping at edges and replaced that awkward bot-refusal text with actual project descriptions. <code>ContributionCubes.jsx</code> got the bulk of it; learned that settling animations need a slower easing curve than the pop-up to feel natural.",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "replaced 13 <code>TODO(impl)</code> stubs with real logic across addressing, headers, pinned blocks, templates, blobs, change detection, markdown, config, journal, orientation, freshness, materialization, and CLI—all 55 unit tests passing. switched from pull-based JIT freshness (ADR-0003) to pre-commit hook regeneration (ADR-0010): <code>.githooks/pre-commit</code> now runs <code>ck ingest && ck materialize --all</code> before every commit, staging changed files; <code>materialize()</code> returns written paths and skips redundant writes via header hash matching. cost was rethinking how documentation stays fresh—gain is deterministic, committed artifacts instead of runtime magic.",
      "project": "context-kernel"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "removed borders from shadow faces and switched to <code>box-shadow</code> for edge lines—turns out <code>padding-box</code> was shifting everything by a pixel. faces now size exactly to <code>cube-depth</code> with no fudge factors, so corners actually meet. net −18 lines of CSS, which felt good until i realized i'd been overthinking the geometry the whole time.",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "fixed markdown code fences leaking into site HTML across all four pipelines. the LLM occasionally wraps responses in <code>```html</code> blocks, so now we strip them in <code>introduce.ts</code>, <code>log_drafter.ts</code>, <code>now_updater.ts</code>, and <code>roadmap_sync.ts</code> before publishing. small regex, big difference in output cleanliness.",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>ripped out all python code (~2144 LOC across 21 files) and retired the <code>EVENTS</code> KV namespace—the bot is now pure cloudflare workers + workflows + d1, no local machine needed. all pipelines already live and verified, so this was just cleanup; the hardest part was accepting that the old architecture actually worked and we could delete it.</p>",
      "project": "evergreenlabs-bot"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>locked <code>Qwen3-30B-A3B-Instruct-2507</code> as S0 default after testing three variants on 42-file corpus: it hit 38.3% cross-scope density with only 2 format warnings, cleanly beating the faster but messier <code>Qwen3.6-35B</code> options. added <code>--cache-ram 0</code> to all llama-server calls (WSL2 was drowning in the default 8 GB prompt cache during ingest). marked S0 complete in <code>PLAN.md</code> and unblocked S1 phase 2 — the cleanliness win cost ~2s per synthesis vs. the speed variant, but extraction quality matters more than throughput here.</p>",
      "project": "context-kernel"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "added <code>spike/spike.py</code> to validate lightrag on lifestrands corpus against s0 exit criteria. qwen3.6-mtp ingests 42 files into 1145 entities &amp; 1195 relationships in ~25 min; cross-scope density hits 43.5% (2.9× the 15% threshold), confirming the kernel's thesis on exposing cross-cutting linkage. the embedding endpoint workaround and occasional 5-field entity tuples from qwen flag two integration points for s1.",
      "project": "context-kernel"
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "ported <code>roadmap_sync</code> from python into the typescript daily-sync pipeline, fetching github projects v2 via graphql and caching llm commentary by <code>updatedAt</code> to skip unchanged items. added a generic <code>ghGraphQL()</code> helper and wired the new step between <code>project_sync</code> and <code>publish</code>, which now merges both datasets into <code>siteData.js</code>—graphql errors log gracefully without crashing the workflow.",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>ported the python <code>now_updater</code> pipeline to typescript, reading the 5 most recent log entries and drafting a fresh \"now\" blurb via llm (temp 0.5, max 200 tokens). the new step slots into <code>per-repo.ts</code> between draft persistence and publish, only firing when there's accepted work to report.</p>\n\n<p>learned that a 10-character sanity floor catches a lot of hallucinated garbage; wiring the now output into the same publish partial means <code>site_parts.now</code> reaches <code>siteData.js</code> in one shot instead of a separate deploy.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "removed the repo whitelist and now track everything, including <code>evergreenlabs-bot</code> itself for dogfooding. the feedback loop guard is now tighter—only skips commits from the github app bot account, letting human-authored commits (even on the bot repo) flow through. simplified the logic and cut 8 lines of config cruft.",
      "project": null
    }
  ],
  "_tracer": {
    "lastTracerRun": "2026-05-24T18:19:53.677Z",
    "kind": "daily-sync",
    "source": "manual",
    "repo": "SirWhack/evergreenlabs-bot",
    "delivery_id": "7dbde3a0-579b-11f1-90a0-e0e6a25445f3"
  }
};
