/* GENERATED by evergreenlabs-bot. Edit data/site/*.json in the bot repo, then `bot publish`.
   Schema: see the website's original siteData.js header for field-by-field comments.
   HTML-bearing fields (now.text, log[].body, project.writeup) are rendered with
   dangerouslySetInnerHTML; treat this file as trusted input. */

export const SITE = {
  "profile": {
    "name": "Sam",
    "fullName": "",
    "location": "Austin, TX",
    "headline": "Software engineer. I build pipelines, agents, and analyzers at work, and a handful of D&D tools on the side. This page is mostly a list of those.",
    "bio": [
      "I'm Sam. I work as a software engineer — mostly on document-processing pipelines and the analyzers that live downstream of them. After hours I keep building things in a similar shape, plus a few tools for the D&D campaign I've been running since 2023.",
      "The projects above are the ones I'm still actively touching. The log is for the small things — what I tried, what didn't work, what I'll come back to. If any of this overlaps with what you're doing, get in touch."
    ],
    "email": "sam@example.com",
    "links": {
      "github": "",
      "linkedin": "",
      "mastodon": "",
      "resume": ""
    }
  },
  "now": {
    "weekOf": "may 24",
    "text": "cleaning up frontend display for <b>evergreenlabs-bot</b>."
  },
  "projects": [],
  "contributions": {
    "totalContributions": 184,
    "fetchedAt": "2026-05-24T00:00:00+00:00",
    "weeks": [
      {
        "week": "2026-02-22",
        "days": [
          {
            "date": "2026-02-22",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-02-23",
            "count": 3,
            "level": 1
          },
          {
            "date": "2026-02-24",
            "count": 1,
            "level": 1
          },
          {
            "date": "2026-02-25",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-02-26",
            "count": 5,
            "level": 2
          },
          {
            "date": "2026-02-27",
            "count": 2,
            "level": 1
          },
          {
            "date": "2026-02-28",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-01",
        "days": [
          {
            "date": "2026-03-01",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-02",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-03",
            "count": 4,
            "level": 2
          },
          {
            "date": "2026-03-04",
            "count": 1,
            "level": 1
          },
          {
            "date": "2026-03-05",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-06",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-07",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-08",
        "days": [
          {
            "date": "2026-03-08",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-09",
            "count": 6,
            "level": 2
          },
          {
            "date": "2026-03-10",
            "count": 9,
            "level": 3
          },
          {
            "date": "2026-03-11",
            "count": 4,
            "level": 2
          },
          {
            "date": "2026-03-12",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-13",
            "count": 1,
            "level": 1
          },
          {
            "date": "2026-03-14",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-15",
        "days": [
          {
            "date": "2026-03-15",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-16",
            "count": 2,
            "level": 1
          },
          {
            "date": "2026-03-17",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-18",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-19",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-20",
            "count": 3,
            "level": 1
          },
          {
            "date": "2026-03-21",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-22",
        "days": [
          {
            "date": "2026-03-22",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-23",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-24",
            "count": 5,
            "level": 2
          },
          {
            "date": "2026-03-25",
            "count": 7,
            "level": 3
          },
          {
            "date": "2026-03-26",
            "count": 2,
            "level": 1
          },
          {
            "date": "2026-03-27",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-28",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-03-29",
        "days": [
          {
            "date": "2026-03-29",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-03-30",
            "count": 1,
            "level": 1
          },
          {
            "date": "2026-03-31",
            "count": 3,
            "level": 1
          },
          {
            "date": "2026-04-01",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-02",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-03",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-04",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-05",
        "days": [
          {
            "date": "2026-04-05",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-06",
            "count": 4,
            "level": 2
          },
          {
            "date": "2026-04-07",
            "count": 2,
            "level": 1
          },
          {
            "date": "2026-04-08",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-09",
            "count": 1,
            "level": 1
          },
          {
            "date": "2026-04-10",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-11",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-12",
        "days": [
          {
            "date": "2026-04-12",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-13",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-14",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-15",
            "count": 1,
            "level": 1
          },
          {
            "date": "2026-04-16",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-17",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-18",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-04-19",
        "days": [
          {
            "date": "2026-04-19",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-20",
            "count": 3,
            "level": 1
          },
          {
            "date": "2026-04-21",
            "count": 8,
            "level": 3
          },
          {
            "date": "2026-04-22",
            "count": 5,
            "level": 2
          },
          {
            "date": "2026-04-23",
            "count": 2,
            "level": 1
          },
          {
            "date": "2026-04-24",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-25",
            "count": 1,
            "level": 1
          }
        ]
      },
      {
        "week": "2026-04-26",
        "days": [
          {
            "date": "2026-04-26",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-27",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-28",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-04-29",
            "count": 2,
            "level": 1
          },
          {
            "date": "2026-04-30",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-01",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-02",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-05-03",
        "days": [
          {
            "date": "2026-05-03",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-04",
            "count": 4,
            "level": 2
          },
          {
            "date": "2026-05-05",
            "count": 6,
            "level": 2
          },
          {
            "date": "2026-05-06",
            "count": 3,
            "level": 1
          },
          {
            "date": "2026-05-07",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-08",
            "count": 1,
            "level": 1
          },
          {
            "date": "2026-05-09",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-05-10",
        "days": [
          {
            "date": "2026-05-10",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-11",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-12",
            "count": 2,
            "level": 1
          },
          {
            "date": "2026-05-13",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-14",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-15",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-16",
            "count": 0,
            "level": 0
          }
        ]
      },
      {
        "week": "2026-05-17",
        "days": [
          {
            "date": "2026-05-17",
            "count": 1,
            "level": 1
          },
          {
            "date": "2026-05-18",
            "count": 0,
            "level": 0
          },
          {
            "date": "2026-05-19",
            "count": 5,
            "level": 2
          },
          {
            "date": "2026-05-20",
            "count": 11,
            "level": 4
          },
          {
            "date": "2026-05-21",
            "count": 7,
            "level": 3
          },
          {
            "date": "2026-05-22",
            "count": 4,
            "level": 2
          },
          {
            "date": "2026-05-23",
            "count": 9,
            "level": 3
          }
        ]
      }
    ]
  },
  "roadmap": [
    {
      "id": "PVTI_lAHOAcFFQc4BYnivzgtopnI",
      "title": "Webhook-triggered autorun via Cloudflare Worker",
      "status": "Todo",
      "priority": null,
      "kind": null,
      "url": "https://github.com/SirWhack/evergreenlabs-bot/issues/2",
      "repo": "SirWhack/evergreenlabs-bot",
      "isDraft": false,
      "commentary": "replace daily cron with push-driven autoruns via github webhooks and a cloudflare worker bridge.",
      "updatedAt": "2026-05-24T02:40:02+00:00"
    }
  ],
  "log": [
    {
      "date": "may 24",
      "year": "2026",
      "body": "ported <code>roadmap_sync</code> from python into the typescript daily-sync pipeline, fetching github projects v2 via graphql and caching llm commentary by <code>updatedAt</code> to skip unchanged items. added a generic <code>ghGraphQL()</code> helper and wired the new step between <code>project_sync</code> and <code>publish</code>, which now merges both datasets into <code>siteData.js</code>—graphql errors log gracefully without crashing the workflow.",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "<p>ported the python <code>now_updater</code> pipeline to typescript, reading the 5 most recent log entries and drafting a fresh \"now\" blurb via llm (temp 0.5, max 200 tokens). the new step slots into <code>per-repo.ts</code> between draft persistence and publish, only firing when there's accepted work to report.</p>\n\n<p>learned that a 10-character sanity floor catches a lot of hallucinated garbage; wiring the now output into the same publish partial means <code>site_parts.now</code> reaches <code>siteData.js</code> in one shot instead of a separate deploy.</p>",
      "project": null
    },
    {
      "date": "may 24",
      "year": "2026",
      "body": "removed the repo whitelist and now track everything, including <code>evergreenlabs-bot</code> itself for dogfooding. the feedback loop guard is now tighter—only skips commits from the github app bot account, letting human-authored commits (even on the bot repo) flow through. simplified the logic and cut 8 lines of config cruft.",
      "project": null
    }
  ],
  "_tracer": {
    "lastTracerRun": "2026-05-24T18:19:53.677Z",
    "kind": "daily-sync",
    "source": "manual",
    "repo": "SirWhack/evergreenlabs-bot",
    "delivery_id": "7dbde3a0-579b-11f1-90a0-e0e6a25445f3"
  }
};
